import os

BEDROCK_API_KEY = os.getenv('BEDROCK_API_KEY', 'ABSKTGktYXQtNDQwNzQ0MjUwNzIwOlRxQkJLWEFIRWFKaGZaU0lsZjF5SlRza1NEK1FIMk9aS1hqUGVyOEhWcVpzTHlzL0t1YnBLKzI4VnZVPQ==')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')

BROWSER_TIMEOUT = 60000
API_TIMEOUT = 60
MAX_TOKENS = 500

DEFAULT_FRAMEWORKS = ['gdpr', 'ccpa']

BROWSER_ARGS = ["--no-sandbox"]

